# Generated by Django 3.2.8 on 2022-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='caption1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='caption2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
