# Generated by Django 3.2.8 on 2022-05-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220512_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
