# Generated by Django 3.2.8 on 2022-05-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
